"""empty message

Revision ID: 402246743d61
Revises: 42f5dbae2602
Create Date: 2025-03-16 12:45:16.332130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402246743d61'
down_revision = '42f5dbae2602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole', schema=None) as batch_op:
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
