"""empty message

Revision ID: 42f5dbae2602
Revises: e7a4646ba8e4
Create Date: 2025-03-16 11:17:58.162195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f5dbae2602'
down_revision = 'e7a4646ba8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole', schema=None) as batch_op:
        batch_op.alter_column('street_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole', schema=None) as batch_op:
        batch_op.alter_column('street_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
