"""empty message

Revision ID: 57afb9a2f258
Revises: 
Create Date: 2025-03-15 22:16:29.129758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57afb9a2f258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('min_danger_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setting')
    # ### end Alembic commands ###
