"""empty message

Revision ID: 8493200123a7
Revises: a41770ebb624
Create Date: 2025-03-16 02:12:26.463868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8493200123a7'
down_revision = 'a41770ebb624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pothole_exist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('pothole_id', sa.Uuid(), nullable=False))
        batch_op.drop_constraint('user_pothole_exist_pid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pothole', ['pothole_id'], ['id'])
        batch_op.drop_column('pid')
        batch_op.drop_column('uid')

    with op.batch_alter_table('user_pothole_fixed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('pothole_id', sa.Uuid(), nullable=False))
        batch_op.drop_constraint('user_pothole_fixed_pid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pothole', ['pothole_id'], ['id'])
        batch_op.drop_column('pid')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pothole_fixed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_pothole_fixed_pid_fkey', 'pothole', ['pid'], ['id'])
        batch_op.drop_column('pothole_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_pothole_exist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_pothole_exist_pid_fkey', 'pothole', ['pid'], ['id'])
        batch_op.drop_column('pothole_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
