"""empty message

Revision ID: 85d391129017
Revises: 8493200123a7
Create Date: 2025-03-16 02:33:48.729755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d391129017'
down_revision = '8493200123a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('user_setting_uid_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_setting_uid_key', ['uid'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
