"""empty message

Revision ID: 8e246c6ab6cb
Revises: 85d391129017
Create Date: 2025-03-16 09:17:20.267355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e246c6ab6cb'
down_revision = '85d391129017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_distance_range', sa.Integer(), nullable=False))
        batch_op.alter_column('min_danger_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.alter_column('min_danger_level',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('pref_distance_range')

    # ### end Alembic commands ###
