"""empty message

Revision ID: a41770ebb624
Revises: 0841c20e893c
Create Date: 2025-03-16 01:28:27.064927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41770ebb624'
down_revision = '0841c20e893c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pothole_exist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('does_exist', sa.Boolean(), nullable=False))
        batch_op.drop_column('doesExist')

    with op.batch_alter_table('user_pothole_fixed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fixed', sa.Boolean(), nullable=False))
        batch_op.drop_column('isFixed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pothole_fixed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isFixed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_fixed')

    with op.batch_alter_table('user_pothole_exist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doesExist', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('does_exist')

    # ### end Alembic commands ###
