"""Pothole Table

Revision ID: c547307dd8e9
Revises: 57afb9a2f258
Create Date: 2025-03-15 22:55:36.627626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c547307dd8e9'
down_revision = '57afb9a2f258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pothole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_uid', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('danger_level', sa.String(length=10), nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pothole_fixed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('pid', sa.Uuid(), nullable=False),
    sa.Column('isFixed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['pothole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pothole_fixed')
    op.drop_table('pothole')
    # ### end Alembic commands ###
